### ISSUE TITLE
unknown error: cannot find MSEdge binary

### ISSUE THREAD

**Issue by he852100** [microsoft/edge-selenium-tools#29]
I set the executable path, it doesn't work
selenium 4
MSEdgeDriver 87.0.664.40
edge beta  87.0.664.40
```
$options.BinaryLocation = "C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe";
```

**Comment by bwalderman** [comment]
Hi @he852100. Please report Selenium 4 issues at the official Selenium repo here: https://github.com/SeleniumHQ/selenium

edge-selenium-tools is a compatibility library to be used with Selenium 3 only. It is not necessary to use this library with Selenium 4 because Selenium 4 already has support for Edge Chromium built in.

**Comment by Maddy820** [comment]
hey i am getting this error in ubuntu. What should i do.
