### ISSUE TITLE
Execution of tests on remote host machine

### ISSUE THREAD

**Issue by MarcelGa** [microsoft/edge-selenium-tools#49]
Hello,
in our team we used chromedriver which executes UI test on embedded cefsharp browser on local and remote machines without any issues.
When we migrate into webview2 browser we switched from chromedriver to edgedriver but only tests which are running locally are successful.
Tests which require execution on remote machines gets this error when constructing edgedriver instance:
 Message: 
```
    OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:56777/session timed out after 60 seconds.
      ----> System.Net.WebException : The request was aborted: The operation has timed out.
    TearDown : System.ServiceModel.CommunicationObjectFaultedException : The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
```

we are using selenium v3 nuget package and  MSEdgeDriver 91.0.864.37

Do you know what could be the problem?

**Comment by bwalderman** [comment]
@MarcelGa please try upgrading your tests to Selenium 4 and see if that resolves the issue. We've shared some instructions for upgrading from Selenium 3 to 4 in ours docs here: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/#upgrading-from-selenium-3

I'm going to close this issue since this project is now deprecated. If the problem still occurs after upgrading, please open a new issue at https://github.com/MicrosoftEdge/WebView2Feedback/issues and we can continue to help you there. If you decide to open a new issue, please include more details about your remote host configuration and a sample of your source code if possible.
