### ISSUE TITLE
Host header or origin header is specified and is not whitelisted or localhost

### ISSUE THREAD

**Issue by bonigarcia** [microsoft/edge-selenium-tools#50]
I have a problem with [msedgedriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/), but I am not sure if this is right place to report it. If it is not, please redirect me to the proper issue tracker.

I'm experiencing the a problem in msedgedriver 92 and 93. It was working fine in msedgedriver 91 and before. It can be reproduced as follows:

1. Start msedgedriver in Linux:
``` 
./msedgedriver --port=4444 --allowed-ips=''
``` 
2. Connect to the URL: http://172.17.0.1:4444/

I need to use the IP `172.17.0.1` (instead of the usual `localhost`) since I run msedgedriver in a Docker container, and I need to request it using the IP address of the gateway between the Docker host and the bridge network (i.e., `172.17.0.1`). 

In msedgedriver 91, it works fine (i.e., the URL before can be requested normally). As of version 92, msedgedriver is not responding correctly. I get the following error in the msedgedriver traces:

```
Starting MSEdgeDriver 92.0.902.45 (ac0e90db3541aec3618593d9b9a1c1ce19757e48) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
[1626189763.900][SEVERE]: Rejecting request with host: 172.17.0.1:4444 address: 172.17.0.1
```

... and I get the following error in the client: `Host header or origin header is specified and is not whitelisted or localhost.`

I've tried to setup the whitelisted IPs (using the argument `--whitelisted-ips=''` when starting msedgedriver) but no luck. Any idea about it?

**Comment by bwalderman** [comment]
Hello @bonigarcia 

Please try without quotes:

```
./msedgedriver --port=4444 --allowed-ips=
```

You should see `All remote connections are allowed. Use an allowlist instead!` in the output if this works.

I'm going to close this issue since this repo is now deprecated and is not intended for general Microsoft Edge driver questions. If you need help in the future, you can contact the Microsoft Edge DevTools team through the "Send feedback" button in Edge: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
