### ISSUE TITLE
Unattended execution not working with Edge 93

### ISSUE THREAD

**Issue by PaulBol** [microsoft/edge-selenium-tools#52]
I found that after updating Edge and the web driver to version 93.0.961.38 test execution in our build pipeline fails. With everything else unchanged (source code, build environment, OS) tests that completed last week are now failing. I am seeing `ElementClickInterceptedException`s and `WebDriverTimeoutException`s when expected content is not detected.

Tests run in Jenkins on a Windows Server machine. When running the tests interactively on my development computer and in a command prompt window on the server everything is fine.

Attempting to get a screenshot to figure out what's happening on the page results in

```text
The HTTP request to the remote WebDriver server for URL http://localhost:62331/session/9ff5f2b91df1a9e969c42489aa96db86/screenshot timed out after 60 seconds.
```

What can I do to restore the functionality or to get to the root cause of the problem?

**Comment by PaulBol** [comment]
I tried running the exact same tests with Google Chrome 93.0.4577.63 and the corresponding web driver. Everything working as expected with Chrome.

**Comment by bwalderman** [comment]
@PaulBol you can try running Microsoft Edge in headless mode. Chrome and Microsoft Edge are not expected to work in headed/interactive mode when running under a service account, which is the case with Jenkins. While this may happen to work for some versions, it is not officially supported.

I'm going to close this issue since this repo is deprecated and is not intended for general Microsoft Edge driver questions. If you need help in the future, you can contact the Microsoft Edge DevTools team through the "Send feedback" button in Edge: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
