### ISSUE TITLE
Cannot able to change the default download directory and browser closes after last command without quit command

### ISSUE THREAD

**Issue by krishna3008** [microsoft/edge-selenium-tools#54]
My code is 
````
from msedge.selenium_tools import Edge, EdgeOptions
from webdriver_manager.microsoft import EdgeChromiumDriverManager
import os, time

options = EdgeOptions()
# options.use_chromium = True
# options.add_argument("headless")
# options.add_argument("disable-gpu")
prefs = {'safebrowsing.enabled': 'false','download.default_directory' : os.getcwd() + os.path.sep}
options.add_experimental_option("prefs", prefs)
options.add_experimental_option("useAutomationExtension", False)

driver.get('https://github.com/')
````

Please help me on this 
I want to run this on headless and download the files to a desired directory
especially from wher the code is triggered

**Comment by bwalderman** [comment]
@krishna3008 I don't see where the driver is created in the sample code, but you need to create and configure the EdgeOptions first, and then pass them to the driver. EdgeOptions cannot be changed after the driver is created. For example:

```python
options = EdgeOptions()
options.add_argument("headless")
prefs = {'safebrowsing.enabled': 'false','download.default_directory' : os.getcwd() + os.path.sep}
options.add_experimental_option("prefs", prefs)

driver = Edge(options = options)
```

I'm going to close this issue since this repo is now deprecated. Please upgrade to Selenium 4 which has built-in support for Microsoft Edge (Chromium). For help with upgrading, see https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/#upgrading-from-selenium-3. If you need further help with this issue, you can contact the Edge DevTools team at https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
