### ISSUE TITLE
Repo still required?

### ISSUE THREAD

**Issue by AutomatedTester** [microsoft/edge-selenium-tools#55]
Hi Folks.

This week Selenium 4 was released to the world. A lot of the code in this repo appears to be workarounds for things that hadn't shipped.

I have done a quick look over the repo and I can't see it's needed and @bwalderman has submitted PRs to Selenium for similar functionality.

If this is no longer needed could we see about archiving this repository?

**Comment by mdmintz** [comment]
And if possible, ship a blank release of ``msedge-selenium-tools`` that doesn't complain about selenium 4.0.0 so that upgrading to selenium 4.0.0 from an existing virtual environment does not have issues. (Unless there's a way to have pip uninstall ``msedge-selenium-tools`` automatically when upgrading to selenium 4).

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.
This behaviour is the source of the following dependency conflicts.
msedge-selenium-tools 3.141.3 requires selenium==3.141, but you have selenium 4.0.0 which is incompatible.
Successfully installed pyOpenSSL-21.0.0 selenium-4.0.0 seleniumbase-2.0.0 trio-0.19.0 trio-websocket-0.9.2
```

CC @bwalderman

**Comment by bwalderman** [comment]
@AutomatedTester, thanks for raising this issue.

Yes, this repo was meant to ensure Edge Chromium support in Selenium 3 while that was the current stable release. Our plan is to deprecate/archive this repo now that Selenium 4 has shipped and help move folks to Selenium 4.

I don't have a concrete timeline as to when that will happen yet. This will require updates to our documentation and we're still investigating the best way to handle things like automatic upgrades. This is definitely on our radar though.

**Comment by bwalderman** [comment]
@mdmintz @AutomatedTester this repo is now officially deprecated, and I've published a final release that logs a warning at either compile-time or runtime depending on the language. We're recommending users upgrade to Selenium 4 going forward.

@mdmintz the pip version conflict you are seeing above is by design. This repo is based on Selenium 3 and won't work once 3 is upgraded to 4, so users will need to uninstall msedge-selenium-tools to upgrading. We've shared some guidance here: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/#upgrading-from-selenium-3
