### ISSUE TITLE
We are using Python roboframework automation. Is it possible to download and install edge driver automatically while script run based on the version passed as parameter?

### ISSUE THREAD

**Issue by neethynair** [microsoft/edge-selenium-tools#56]
We are using Python robot framework automation. Is it possible to download and install edge driver automatically while script run based on the version passed as parameter?We are using selenium 3.14 , robot framework selenium library 4.5.0 and python 3.7

**Comment by bwalderman** [comment]
@neethynair you can use [WebDriverManager](https://bonigarcia.dev/webdrivermanager/) which is a 3rd-party tool that can automatically manage drivers for all browsers including Microsoft Edge.

I'm going to close this issue since this repo is now deprecated. We're recommending users upgrade their tests to Selenium 4. If you need further help with the Microsoft Edge driver, you can contact the DevTools team at https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
