### ISSUE TITLE
Turn off remote debugging mode - MSEdge Driver - SAP Portal

### ISSUE THREAD

**Issue by devqaio** [microsoft/edge-selenium-tools#57]
I am trying to automate a SAP web portal (NetWeaver) using Selenium WebDriver 3.141.59 (Java binding). Upon navigating to the portal,  it shows a message on screen saying "Could not open iView. The iView is not compatible with your browser, operating system, or device. Contact your system administrator for more information."

Also, on top it shows a ribbon with message "turn off remote debugging to open this site in internet explorer mode".

However, with regular browser session, it works fine. 

Should I use any specific capabilities/option while creating EdgeDriver instance?

**Comment by trontronicent** [comment]
Only an assumption, as I have no possibility to check the target...
By default. Webdriver implementations change the property 'Webdriver' of the Browser-internal "Navigator" object to explicitly show that the browser is automated through Webdriver. 

So, what u could try (works at least with Edge Chromium)
- Add a JS script to evaluate on page load, which overrides the 'Webdriver' property-getter  of the navigator object,  through the ExecuteChromiumCommand() method before loading your first site.  Here's how I do it in C# - should work with Java too, I assume.
`(Webdriver as EdgeDriver).ExecuteChromiumCommand(
                                                                        "Page.addScriptToEvaluateOnNewDocument",
                                                                        new Dictionary<string, object>
                                                                        {
                                                                            {
                                                                                "source",
                                                                                "Object.defineProperty(navigator, 'webdriver',  {" +
                                                                                "get:" +
                                                                                $"() => false" +
                                                                                "})"
                                                                            }
                                                                        });`

what it does, is actually using the internal DevTools protocol connection to execute the "Page.addScriptToEvaluateOnNewDocument" command with with the given parameterDictionary. The value for key 'source' then is absolute raw JavaScript that gets evaluated on each new document (iframes, sub-documents etc.).

**Comment by bwalderman** [comment]
@gitissuepost it looks like you have Edge configured to open the portal page in Internet Explorer mode. But launching Edge with EdgeDriver prevents Internet Explorer mode from working. To test IE mode pages, you will need to use Internet Explorer Driver v4.0.0 instead of EdgeDriver. See instructions here: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode

I'm going to close this issue since this repo is now deprecated and we're recommending users upgrade to Selenium 4 for testing with Edge. If you need help after upgrading, you can open a new issue in the official Selenium repo at https://github.com/SeleniumHQ/selenium/issues or contact the Edge DevTools team at https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
